In [1]:
#Data.csv

**Step 1: Importing the libraries**

In [2]:
import numpy as np
import pandas as pd
import matplotlib.pyplot as plt



**Step 2: Importing dataset**

In [3]:
df=pd.read_csv("/content/Data.csv")

In [4]:
df

Country   Age   Salary Purchased
0   France  44.0  72000.0        No
1    Spain  27.0  48000.0       Yes
2  Germany  30.0  54000.0        No
3    Spain  38.0  61000.0        No
4  Germany  40.0      NaN       Yes
5   France  35.0  58000.0       Yes
6    Spain   NaN  52000.0        No
7   France  48.0  79000.0       Yes
8  Germany  50.0  83000.0        No
9   France  37.0  67000.0       Yes

In [5]:
x= df.iloc[:,:-1].values
y= df.iloc[:,-1].values


In [6]:
#Independent variable:
print(x)

[['France' 44.0 72000.0]
 ['Spain' 27.0 48000.0]
 ['Germany' 30.0 54000.0]
 ['Spain' 38.0 61000.0]
 ['Germany' 40.0 nan]
 ['France' 35.0 58000.0]
 ['Spain' nan 52000.0]
 ['France' 48.0 79000.0]
 ['Germany' 50.0 83000.0]
 ['France' 37.0 67000.0]]


In [7]:
#Dependent or to be predicted feature will be:
print(y)

['No' 'Yes' 'No' 'No' 'Yes' 'Yes' 'No' 'Yes' 'No' 'Yes']


**Step 3: Handling the missing data**

In [8]:
df.isnull()

Country    Age  Salary  Purchased
0    False  False   False      False
1    False  False   False      False
2    False  False   False      False
3    False  False   False      False
4    False  False    True      False
5    False  False   False      False
6    False   True   False      False
7    False  False   False      False
8    False  False   False      False
9    False  False   False      False

In [9]:
from sklearn.impute import SimpleImputer
imputer= SimpleImputer(missing_values=np.nan, strategy="mean")
imputer.fit(x[:,1:3]) 
x[:,1:3]= imputer.transform(x[:,1:3])

In [10]:
x

array([['France', 44.0, 72000.0],
       ['Spain', 27.0, 48000.0],
       ['Germany', 30.0, 54000.0],
       ['Spain', 38.0, 61000.0],
       ['Germany', 40.0, 63777.77777777778],
       ['France', 35.0, 58000.0],
       ['Spain', 38.77777777777778, 52000.0],
       ['France', 48.0, 79000.0],
       ['Germany', 50.0, 83000.0],
       ['France', 37.0, 67000.0]], dtype=object)

The above null values are the mean value of that particular column which was replaced with it

**Step 4: Encoding categorical data**

In [11]:
from sklearn.compose import ColumnTransformer
from sklearn.preprocessing import OneHotEncoder
#create a object for column transformer
ct = ColumnTransformer(transformers=[("encoder", OneHotEncoder(),[0])],remainder="passthrough")
x = ct.fit_transform(x)


In [12]:
x

array([[1.0, 0.0, 0.0, 44.0, 72000.0],
       [0.0, 0.0, 1.0, 27.0, 48000.0],
       [0.0, 1.0, 0.0, 30.0, 54000.0],
       [0.0, 0.0, 1.0, 38.0, 61000.0],
       [0.0, 1.0, 0.0, 40.0, 63777.77777777778],
       [1.0, 0.0, 0.0, 35.0, 58000.0],
       [0.0, 0.0, 1.0, 38.77777777777778, 52000.0],
       [1.0, 0.0, 0.0, 48.0, 79000.0],
       [0.0, 1.0, 0.0, 50.0, 83000.0],
       [1.0, 0.0, 0.0, 37.0, 67000.0]], dtype=object)

**Step 5: Creating a dummy variable**

In [13]:
from sklearn.preprocessing import LabelEncoder
label = LabelEncoder()
y = label.fit_transform(y)

In [14]:
y

array([0, 1, 0, 0, 1, 1, 0, 1, 0, 1])

As you can see in the above output yes/ no got changed into binary 0,1.

**Step 6: Splitting the datasets into training sets and Test sets**

In [15]:
from sklearn.model_selection import train_test_split
X_train, X_test, y_train, y_test = train_test_split(x, y, test_size=0.30)

In [16]:
print(X_train)

[[0.0 0.0 1.0 38.0 61000.0]
 [1.0 0.0 0.0 44.0 72000.0]
 [0.0 1.0 0.0 40.0 63777.77777777778]
 [1.0 0.0 0.0 37.0 67000.0]
 [0.0 0.0 1.0 27.0 48000.0]
 [0.0 1.0 0.0 50.0 83000.0]
 [0.0 0.0 1.0 38.77777777777778 52000.0]]


In [17]:
print(y_train)

[0 0 1 1 1 0 0]


In [18]:
print(X_test)

[[1.0 0.0 0.0 48.0 79000.0]
 [1.0 0.0 0.0 35.0 58000.0]
 [0.0 1.0 0.0 30.0 54000.0]]


In [19]:
print(y_test)

[1 1 0]


**Step 7: Feature Scaling**

In [20]:
from sklearn.preprocessing import StandardScaler, MinMaxScaler
standard = StandardScaler()
X_train[:,3:] = standard.fit_transform(X_train[:,3:])
X_test[:,3:] = standard.transform(X_test[:,3:])

In [21]:
X_train

array([[0.0, 0.0, 1.0, -0.1929678249497467, -0.25748796781410355],
       [1.0, 0.0, 0.0, 0.7303465779743584, 0.7449792327205825],
       [0.0, 1.0, 0.0, 0.11480364269162167, -0.004339684850798686],
       [1.0, 0.0, 0.0, -0.3468535587704309, 0.2893123233866343],
       [0.0, 0.0, 1.0, -1.885710896977273, -1.442221932082369],
       [0.0, 1.0, 0.0, 1.6536609808984635, 1.7474464332552686],
       [0.0, 0.0, 1.0, -0.07327892086699221, -1.0776884046152104]],
      dtype=object)

In [22]:
X_test

array([[1.0, 0.0, 0.0, 1.3458895132570952, 1.38291290578811],
       [1.0, 0.0, 0.0, -0.6546250264117993, -0.5308881134144725],
       [0.0, 1.0, 0.0, -1.4240536955152203, -0.8954216408816311]],
      dtype=object)

In [23]:
minmax = MinMaxScaler()
X_train = minmax.fit_transform(X_train)
X_test = minmax.transform(X_test)

In [24]:
print(X_train)

[[0.         0.         1.         0.47826087 0.37142857]
 [1.         0.         0.         0.73913043 0.68571429]
 [0.         1.         0.         0.56521739 0.45079365]
 [1.         0.         0.         0.43478261 0.54285714]
 [0.         0.         1.         0.         0.        ]
 [0.         1.         0.         1.         1.        ]
 [0.         0.         1.         0.51207729 0.11428571]]


In [25]:
print(X_test)

[[1.         0.         0.         0.91304348 0.88571429]
 [1.         0.         0.         0.34782609 0.28571429]
 [0.         1.         0.         0.13043478 0.17142857]]
